---

- name: Launch app container
  docker_container:
    name: simple-api  
    image: aminedocker2/tp-devops-simple-api:latest
    pull: true
    env:
      DATABASE_HOST: tp_database 
      DATABASE_PORT: "{{ lookup('env', 'DATABASE_PORT') }}"
      DATABASE_NAME: "{{ lookup('env', 'DATABASE_NAME') }}"
      DATABASE_USERNAME: "{{ lookup('env', 'DATABASE_USERNAME') }}"
      DATABASE_PASSWORD: "{{ lookup('env', 'DATABASE_PASSWORD') }}"
    networks:
      - name: my_network
    published_ports:
      - "8080:8080"
    state: started
