name: CI devops 2025

on:
  push:
    branches: [ main, develop ]
  pull_request:


jobs:
  test-backend:
    runs-on: ubuntu-24.04
    environment: development

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Build and test with Maven
      run: |
        cd simple-api
        mvn clean verify

    - name: Check quality with Sonar
      run: mvn -B verify sonar:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECTKEY }} -Dsonar.organization=${{ secrets.ORGANISATION }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./simple-api/pom.xml


    #OWAPS, pourcentage