name: CI devops 2025
on:
  #These jobs will be launched on main and develop
  push:
    branches: [ main, develop ]
  pull_request:


jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
    #checkout the github code using actions/checkout@v4
    - uses: actions/checkout@v4

    #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
      #finally build your app with the latest command
    - name: Build and test with Maven
      run: |
        cd simple-api
        mvn clean verify
